import pandas as pd
import numpy as np

def extraer_dato_robusto(df, terminos, cols):
    patron = "(?i)" + "|".join(terminos) # (?i) hace que sea case-insensitive
    mask = pd.Series(False, index=df.index)
    
    for meta_col in ["concept", "standard_concept", "label"]:
        if meta_col in df.columns:
            mask = mask | df[meta_col].astype(str).str.contains(patron, na=False, regex=True)
            
    fila = df[mask]
    if not fila.empty:
        # Forzar numérico y quitar basura
        df_num = fila[cols].astype(str).replace({',': '', '\$': ''}, regex=True).apply(pd.to_numeric, errors='coerce')
        # Buscar la fila con la mayor suma absoluta (evita filas de subtotales vacíos)
        mejor_fila = df_num.assign(suma=df_num.abs().sum(axis=1)).sort_values("suma", ascending=False).drop(columns=["suma"]).iloc[0]
        return mejor_fila
        
    return pd.Series([0.0] * len(cols), index=cols) # Retornar 0 en vez de NaN para evitar romper cálculos

def analizar_flujo_efectivo(cf_df, is_df):
    if cf_df is None or is_df is None: return None

    cols_cf = sorted([c for c in cf_df.columns if str(c).isdigit() and len(str(c)) == 4])
    cols_is = sorted([c for c in is_df.columns if str(c).isdigit() and len(str(c)) == 4])

    capex = extraer_dato_robusto(cf_df, ['PaymentsToAcquirePropertyPlantAndEquipment', 'PaymentsToAcquireProductiveAssets', 'Purchases of property', 'Capital expenditures', 'Additions to property'], cols_cf)
    recompras = extraer_dato_robusto(cf_df, ['PaymentsForRepurchaseOfCommonStock', 'PaymentsForRepurchaseOfEquity', 'Repurchases of common stock', 'Repurchases of common', 'Treasury stock acquired'], cols_cf)
    fco = extraer_dato_robusto(cf_df, ['NetCashProvidedByOperatingActivities', 'Cash generated by operating activities', 'Net cash provided by operating activities', 'Cash flows from operating activities'], cols_cf)
    beneficio_neto = extraer_dato_robusto(is_df, ['NetIncomeLoss', 'NetIncomeLossAvailableToCommonStockholdersBasic', 'ProfitLoss', 'Net income', 'Net earnings'], cols_is)
    dividendos = extraer_dato_robusto(cf_df, ['PaymentsOfDividendsCommonStock', 'PaymentsOfDividends', 'DividendsPaid', 'Cash dividends paid', 'Payment of dividends'], cols_cf)
    
    depreciacion = extraer_dato_robusto(cf_df, ["DepreciationDepletionAndAmortization", "DepreciationAndAmortization", "DepreciationAmortizationAndAccretion", "Depreciation", "Amortization"], cols_cf).abs()

    # Alinear al mismo índice de años
    beneficio_neto_aligned = pd.Series(index=cols_cf, dtype=float)
    for c in cols_cf:
        coincidencias = [is_col for is_col in cols_is if str(c)[:4] in str(is_col)]
        if coincidencias: beneficio_neto_aligned[c] = beneficio_neto[coincidencias[0]]

    df_cf_ratios = pd.DataFrame(index=cols_cf)

    df_cf_ratios['CAPEX % sobre Beneficio'] = (capex.abs() / beneficio_neto_aligned.replace(0, np.nan) * 100).fillna(0)
    df_cf_ratios['Recompras (B USD)'] = recompras.abs() / 1e9
    df_cf_ratios['Free Cash Flow (B USD)'] = (fco - capex.abs()) / 1e9
    
    # Guardar valores absolutos para la Cascada
    df_cf_ratios['CFO (B USD)'] = fco / 1e9
    df_cf_ratios['CAPEX (B USD)'] = capex.abs() / 1e9
    df_cf_ratios['Dividendos (B USD)'] = dividendos.abs() / 1e9

    # Cálculo de Owner Earnings (Buffett 1986)
    capex_abs = capex.abs()
    capex_mantenimiento = depreciacion.combine(capex_abs, min) 
    df_cf_ratios['Owner Earnings (B USD)'] = (fco - capex_mantenimiento) / 1e9

    media_capex = df_cf_ratios['CAPEX % sobre Beneficio'].mean()
    if media_capex == 0: status = "Sin datos de CAPEX suficientes"
    elif media_capex < 25: status = "Ventaja Duradera (CAPEX < 25%)"
    elif media_capex < 50: status = "Empresa Saludable (CAPEX 25–50%)"
    else: status = "Alta Intensidad de Capital (CAPEX > 50%)"

    return {"ratios": df_cf_ratios.round(2), "veredicto": status}